spring:
 profiles:
    active: local
    
--- ## local 환경
# DB설정
# properties 파일로 할 때
#spring.datasource.username=itest
#spring.datasource.password=dusrn1
#spring.datasource.url=jdbc:mariadb://mxm.kr:23306/itest
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# properties 파일로 하고 hikariCP 사용 때
#spring.datasource.hikari.username=itest
#spring.datasource.hikari.password=dusrn1
#spring.datasource.hikari.jdbc-url=jdbc:mariadb://mxm.kr:23306/itest
#spring.datasource.hikari.driver-class-name=org.mariadb.jdbc.Driver
spring: 
  profiles: local
  datasource:
    hikari:
      username: itest
      password: dusrn1
      jdbc-url: jdbc:log4jdbc:mariadb://mxm.kr:23306/itest
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
     #username: root
     #password: qufdl123456!
     #jdbc-url: jdbc:mariadb://localhost:3306/webdb
     #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
     #jdbc-url : jdbc:mariadb://mxm.kr:23306/itest
     #driver-class-name : org.mariadb.jdbc.Driver 
     
  security:
    user:
      name: user
      password: test
      
spring.profiles.include: console-logging

--- ## 개발환경
spring:
  profiles: dev

#spring.profiles.include: console-logging, file-logging

